package gui;

import java.awt.HeadlessException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.json.JSONObject;

import restful.RestServices;

public class TelaPrincipal extends javax.swing.JFrame {
    String user;
    
    RestServices rest;
    JSONObject agencia;
    JSONObject conta;    
    
    DefaultListModel modelListaLeiloes = new DefaultListModel();
    DefaultTableModel modeloTable;

    public TelaPrincipal() throws HeadlessException {
    }
    
    public TelaPrincipal(RestServices rest, JSONObject agencia, JSONObject conta) {
        this.rest = rest;
        this.agencia = agencia;
        this.conta = conta;
       
        
        initComponents();

        statusLabel.setText("Pronto!");
        accountLabel.setText(""+conta.getInt("id"));
        userLabel.setText(conta.getString("nome_cliente"));
        bankLabel.setText(agencia.getString("nome_banco"));
        agencyLabel.setText(""+agencia.getInt("id"));
        
       
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        accountLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bankLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        agencyLabel = new javax.swing.JLabel();
        buttonSaldo = new javax.swing.JButton();
        buttonDeposito = new javax.swing.JButton();
        buttonSaque = new javax.swing.JButton();
        buttonTransf = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        contaDepTextField = new javax.swing.JTextField();
        valorDepTextField = new javax.swing.JTextField();
        contaAlvoTraTextField = new javax.swing.JTextField();
        valorTraTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        transfComboBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        valorSaqTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        deposComboBox = new javax.swing.JComboBox<>();
        tipoContaBox = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        titulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        titulo.setText("TopBank!");

        userLabel.setText("USUARIO: "+user);

        jButtonSair.setText("SAIR");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jLabel4.setText("Status: ");

        statusLabel.setText("status");

        jLabel2.setText("Usuário: ");

        accountLabel.setText("<Account Code>");

        jLabel3.setText("Nº Conta:");

        jLabel5.setText("Banco:");

        bankLabel.setText("<Bank Code>");

        jLabel6.setText("Nº Agência:");

        agencyLabel.setText("<Agency Code>");

        buttonSaldo.setText("Consultar");
        buttonSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaldoActionPerformed(evt);
            }
        });

        buttonDeposito.setText("Depositar");
        buttonDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDepositoActionPerformed(evt);
            }
        });

        buttonSaque.setText("Saque");
        buttonSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaqueActionPerformed(evt);
            }
        });

        buttonTransf.setText("Transferir");
        buttonTransf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTransfActionPerformed(evt);
            }
        });

        jLabel1.setText("Conta alvo:");

        jLabel7.setText("Valor:");

        jLabel8.setText("Conta alvo:");

        jLabel9.setText("Valor:");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("Minha Conta");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setText("Transferências");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setText("Depósitos");

        contaDepTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contaDepTextFieldActionPerformed(evt);
            }
        });

        valorDepTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorDepTextFieldActionPerformed(evt);
            }
        });

        contaAlvoTraTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contaAlvoTraTextFieldActionPerformed(evt);
            }
        });

        valorTraTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorTraTextFieldActionPerformed(evt);
            }
        });

        jLabel13.setText("Tipo transf:");

        transfComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cc p/ Cc", "Cc p/ P", "DOC", "TED" }));
        transfComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transfComboBoxActionPerformed(evt);
            }
        });

        jLabel14.setText("Valor:");

        valorSaqTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorSaqTextFieldActionPerformed(evt);
            }
        });

        jLabel15.setText("Tipo depos:");

        deposComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Poupanca", "Corrente" }));

        tipoContaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Poupanca", "Corrente" }));

        jLabel16.setText("Saldo:");

        jLabel17.setText("Tipo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(valorSaqTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tipoContaBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buttonSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deposComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(valorDepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(contaDepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel12))))
                            .addComponent(buttonDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(transfComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(contaAlvoTraTextField)
                                    .addComponent(valorTraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel11))
                            .addComponent(buttonTransf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(userLabel)
                                        .addComponent(accountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bankLabel))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(agencyLabel)))
                            .addGap(176, 176, 176))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(titulo)
                            .addGap(138, 138, 138)
                            .addComponent(jButtonSair)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSair)
                        .addGap(30, 30, 30))
                    .addComponent(titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(bankLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(agencyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(tipoContaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(buttonSaldo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(valorSaqTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(contaAlvoTraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(3, 3, 3)
                                            .addComponent(valorTraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(7, 7, 7)
                                            .addComponent(jLabel9)))
                                    .addGap(1, 1, 1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(contaDepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(valorDepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(deposComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(69, 69, 69))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(transfComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(buttonTransf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statusLabel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        
        System.exit(0);        
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void buttonDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDepositoActionPerformed
        
        String tipoDeposito = (String) deposComboBox.getSelectedItem() ;
        JSONObject conta_destino = new JSONObject();
        double novo_saldo = 0;
        
        if (contaDepTextField.getText().isEmpty() || valorDepTextField.getText().isEmpty() || tipoDeposito.isEmpty()){
            JOptionPane.showMessageDialog(this, "Insira as infos para deposito!");
            return;
        }
            
        double deposito = Double.parseDouble(valorDepTextField.getText());          
        String id_dest = contaDepTextField.getText();
        
        try {
            conta_destino = rest.getMethod(rest.getServices().getString("contas")+id_dest+"");
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String tipo_conta = (String) deposComboBox.getSelectedItem();       
                              
        conta_destino.put("valor_deposito", deposito);
        conta_destino.put("tipo_conta", tipo_conta);  
        conta_destino.put("tipo_op", "deposito");
               
        try {
            conta = rest.getMethod(rest.getServices().getString("contas")+conta.getInt("id"));
            conta = rest.putMethod(rest.getServices().getString("contas")+id_dest+"/", conta_destino);
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        statusLabel.setText("Deposito realizado com sucesso!");         
    }//GEN-LAST:event_buttonDepositoActionPerformed

    private void buttonSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaldoActionPerformed
       
         try {
            conta = rest.getMethod(rest.getServices().getString("contas")+conta.getInt("id"));
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(tipoContaBox.getSelectedItem().toString().equals("Poupanca"))
            JOptionPane.showMessageDialog(this, "Saldo da conta poupança é: R$" + conta.getDouble("saldo_poupanca"));
        else
            JOptionPane.showMessageDialog(this, "Saldo da conta corrente é: R$" + conta.getDouble("saldo_corrente")); 
    }//GEN-LAST:event_buttonSaldoActionPerformed

    private void buttonSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaqueActionPerformed
        if (valorSaqTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Insira um valor para saque!");
            return;
        }
        
        JSONObject conta_saque = new JSONObject();
        
        try {
            conta_saque = rest.getMethod(rest.getServices().getString("contas")+conta.getInt("id")+"");
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }        
        String tipo_conta = (String) tipoContaBox.getSelectedItem();
        
        conta_saque.put("valor_saque", Float.parseFloat(valorSaqTextField.getText()));        
        conta_saque.put("tipo_conta", tipo_conta);  
        conta_saque.put("tipo_op", "saque");
        
        try {
            //conta = rest.getMethod(rest.getServices().getString("contas")+conta.getInt("id"));
            conta = rest.putMethod(rest.getServices().getString("contas")+conta.getInt("id")+"/", conta_saque);
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        //statusLabel.setText("Saque realizado com sucesso!");
        JOptionPane.showMessageDialog(this, "Saque realizado com sucesso!");
    }//GEN-LAST:event_buttonSaqueActionPerformed

    private void contaDepTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contaDepTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contaDepTextFieldActionPerformed

    private void valorDepTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorDepTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorDepTextFieldActionPerformed

    private void contaAlvoTraTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contaAlvoTraTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contaAlvoTraTextFieldActionPerformed

    private void valorTraTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorTraTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorTraTextFieldActionPerformed

    private void valorSaqTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorSaqTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorSaqTextFieldActionPerformed

    private void transfComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transfComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transfComboBoxActionPerformed

    private void buttonTransfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTransfActionPerformed
        if (valorTraTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Insira um valor para transferência!");
            return;
        }
        
        JSONObject conta_origem = new JSONObject();
        
        try {
            conta_origem = rest.getMethod(rest.getServices().getString("contas")+conta.getInt("id")+"");
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }        
        String tipo_transf = (String) transfComboBox.getSelectedItem();
        
        conta_origem.put("valor_saque", Float.parseFloat(valorSaqTextField.getText()));        
        conta_origem.put("tipo_transf", tipo_transf);
        conta_origem.put("conta_dest", Integer.parseInt(contaAlvoTraTextField.getText()));
        conta_origem.put("tipo_op", "transf");
        
        try {
            //conta = rest.getMethod(rest.getServices().getString("contas")+conta.getInt("id"));
            conta = rest.putMethod(rest.getServices().getString("contas")+conta.getInt("id")+"/", conta_origem);
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        //statusLabel.setText("Saque realizado com sucesso!");
        JOptionPane.showMessageDialog(this, "Saque realizado com sucesso!");
    }//GEN-LAST:event_buttonTransfActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountLabel;
    private javax.swing.JLabel agencyLabel;
    private javax.swing.JLabel bankLabel;
    private javax.swing.JButton buttonDeposito;
    private javax.swing.JButton buttonSaldo;
    private javax.swing.JButton buttonSaque;
    private javax.swing.JButton buttonTransf;
    private javax.swing.JTextField contaAlvoTraTextField;
    private javax.swing.JTextField contaDepTextField;
    private javax.swing.JComboBox<String> deposComboBox;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JComboBox<String> tipoContaBox;
    private javax.swing.JLabel titulo;
    private javax.swing.JComboBox<String> transfComboBox;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField valorDepTextField;
    private javax.swing.JTextField valorSaqTextField;
    private javax.swing.JTextField valorTraTextField;
    // End of variables declaration//GEN-END:variables
}
