# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100, verbose_name='nome do cliente')),
                ('saldo', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'contas',
                'verbose_name': 'conta',
            },
        ),
    ]
