# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_agencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='agencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Agencia'),
        ),
    ]
