# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_conta_agencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('cc', 'Conta corrente - Conta corrente'), ('cp', 'Conta corrente - Conta poupança'), ('doc', 'DOC'), ('ted', 'TED')], default='', max_length=20, verbose_name='tipos de transferencia')),
            ],
        ),
        migrations.RemoveField(
            model_name='conta',
            name='saldo',
        ),
        migrations.AddField(
            model_name='conta',
            name='saldo_corrente',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conta',
            name='saldo_poupanca',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='conta_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Conta'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='conta_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_requests_created', to='server.Conta'),
        ),
    ]
